name: github pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip3 install -U -r requirements.txt
        working-directory: src

      - name: Build
        run: make github
        working-directory: src

      - name: Deploy
        run: |
          git add docs
          git commit -m "docs: deploy ${GITHUB_SHA}"
          git push origin main
